#!/usr/bin/ruby -w
# 
# ruffle - a rubyfied Pacman package analyzer
# Copyright (C) 2008 Colin Gan <laxatives@gmail.com>
# 
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#require 'zlib'
require 'rubygems'
require 'fileutils'
#
#this is an ugly way of getting the rule modules easily...
#Dir.glob(File.dirname(__FILE__) + '/ruffle_rules/*.rb').each {|rule| require rule} 
Dir.glob('/home/colin/projects/ruffle/ruffle_rules/*.rb').each {|rule| require rule} 
#require 'ruffle_rules/permissions'

class Ruffle
  def initialize(package_name)
    #@sandbox = '/home/colin/sandbox_namcap/'
    @sandbox = Dir::tmpdir + '/ruffle_' + Process.pid
    @package_path = package_name
    #@package_path = '/home/colin/builds/PACKAGE_CACHE/libxft-2.1.13-2-i686.pkg.tar.gz'
    #@package_path = '/home/colin/builds/PACKAGE_CACHE/pcmanfm-0.5-3-i686.pkg.tar.gz'
    #@package_path = '/home/colin/builds/PACKAGE_CACHE/shoes-2-1-i686.pkg.tar.gz'
    #@package_path = '/home/colin/builds/PACKAGE_CACHE/xorg-server-1.5.3-4-i686.pkg.tar.gz'
    #@package_path = '/home/colin/builds/PACKAGE_CACHE/xulrunner-1.9.0.4-3-i686.pkg.tar.gz'
    @files = []
  end

  def open_package
    if not File.exist?(@sandbox)
      Dir.mkdir(@sandbox) 
    end
  end

  def view_files
    # files[filenumber][n], where n:
    # 0 --> readwriteexec string
    # 1 --> ownership
    # 2 --> size
    # 3 --> date
    # 4 --> time
    # 5 --> filepath
    # 6 --> symlink arrow
    # 7 --> actual filepath
    `tar -tvf #{@package_path}`.split("\n").each {|x| @files << x.split(" ")}
    Permissions.check(@files)
    Depends.analyze(@files)
    #Depends.get_files(@files)
  end

  def check_p_info
    package_info = "#{@sandbox}/.PKGINFO" 
    pkginfo_vars = [:pkgname, :pkgver, :pkgdesc, :url, :builddate, :packager, :size, :arch, :license, :depend, :optdepend] 
    pkginfo_hash = {}
    
    if File.exist?(package_info)
      puts "Package info exists!"

      begin
        File.open(package_info).each do |x|
          #x.scan(/(.*)? = (.*)/) {|x, y| puts x + "~~~" + y}
          pkginfo_vars.each do |var|
            x.scan(/#{var} = (.*)/) {|val| pkginfo_hash[var] = val} 
          end
        end
        pkginfo_hash.each_pair {|x,y| puts "#{x} = #{y}"}
      end

    end
    #remove for now
    #FileUtils.rm_r(@sandbox, :secure => true)
  end
  
  def extract_pkginfo
  
  `tar -xf #{@package_path} .PKGINFO`

  end

end

r_namcap = Ruffle.new(ARGV[0])

#r_namcap.open_package
#r_namcap.check_p_info
r_namcap.view_files
